### ISSUE TITLE
Transaction Fees

### ISSUE THREAD

**Issue by eschiendorfer** [mollie/thirtybees#1]
Could you add a feature, that merchant can add a "fee" per payment method? Example: It should be possible to charge 2% from paypal customers, but not from credit cards.

**Comment by snowycatsoftware** [comment]
Hi @eschiendorfer ,

According to the PSD2 a webshop can not charge a transaction fee to customers anymore. Therefore, we can not implement this feature. If you do wish to charge your customers a transaction fee, you could look for a payment fee module: https://addons.prestashop.com/en/search?search_query=payment%20fee

We will close this issue. If you have any questions, please let us know.

Kind Regards

**Comment by eschiendorfer** [comment]
@snowycatsoftware thanks for your answer! this won't work I guess. Since mollie is recognized as one payment module or am I wrong?

**Comment by snowycatsoftware** [comment]
Hi @eschiendorfer,

It's always difficult to determine if a module will or will not work. Like you said, it's one payment module so it's hard to estimate if it will hook into each payment method per module or will only recognise the module itself. You could always hire a developer to achieve this if you do insist on charging your customers a transaction fee.

Kind Regards
